import http from "node:http";
import { readFileSync, existsSync, statSync, mkdtempSync } from "node:fs";
import { join, extname } from "node:path";
import { tmpdir } from "node:os";
import chromium from "@sparticuz/chromium";
import puppeteer from "puppeteer-core";
const DIST = join(process.cwd(), "dist");
const TYPES = { ".html":"text/html",".js":"text/javascript",".css":"text/css",".json":"application/json",".svg":"image/svg+xml",".png":"image/png",".webmanifest":"application/manifest+json",".map":"application/json" };
const server = http.createServer((req, res) => { let p=decodeURIComponent((req.url||"/").split("?")[0]).replace(/^\/MAX-Finder\//,"/").replace(/^\/+/,""); let f=join(DIST,p); if(!existsSync(f)||statSync(f).isDirectory()) f=join(DIST,"index.html"); res.writeHead(200,{"Content-Type":TYPES[extname(f)]||"application/octet-stream"}); res.end(readFileSync(f)); });
await new Promise(r=>server.listen(0,"127.0.0.1",r));
const BASE=`http://127.0.0.1:${server.address().port}/MAX-Finder/`;
const P=encodeURIComponent("PARIS (intramuros)"), M=encodeURIComponent("MARSEILLE ST CHARLES"), V=encodeURIComponent("LYON (intramuros)");
const D=new Date(Date.now()+3*86400000).toISOString().slice(0,10);
const args=chromium.args.filter(a=>!a.startsWith("--user-data-dir")&&!a.startsWith("--proxy"));
const browser=await puppeteer.launch({args:[...args,"--no-sandbox","--disable-setuid-sandbox","--no-proxy-server"],executablePath:await chromium.executablePath(),headless:true,userDataDir:mkdtempSync(join(tmpdir(),"l-"))});
const page=await browser.newPage(); await page.setCacheEnabled(false);
await page.setViewport({width:820,height:1100,deviceScaleFactor:2});
await page.goto(`${BASE}?mode=od&from=${P}&to=${M}&via=${V}&conn=1&date=${D}`,{waitUntil:"domcontentloaded",timeout:60000}).catch(()=>{});
await page.waitForFunction(()=>document.querySelector(".journey"),{timeout:60000}).catch(()=>{});
const r=await page.evaluate(()=>{ const j=document.querySelector(".main-col .journey"); if(!j) return "no journey"; return { legs:j.querySelectorAll(".leg").length, legBookBtns:j.querySelectorAll(".btn-leg-book").length, wholeBookInActions: !!j.querySelector(".actions .btn-book:not(.btn-leg-book)"), legBookHrefs:[...j.querySelectorAll(".btn-leg-book")].map(a=>decodeURIComponent(new URL(a.href).searchParams.get("userInput"))) }; });
console.log(JSON.stringify(r,null,1));
const jcard=await page.$(".main-col .journey"); await (jcard??page).screenshot({path: process.env.SD + "/leg-book.png"});
await browser.close(); server.close();
